### ISSUE TITLE
augmentation.py returns an empty folders

### ISSUE THREAD

**Issue by assia855** [mmstfkc/yolov8-segmentation-augmentation#2]
Thanks for sharing your work. Can you please provide an explanation to why the code doesn't generate the augmented images and their labels.

**Comment by mmstfkc** [comment]
Hello. Since it is still under development, for now, certain areas are closed with a comment line. According to the current structure, if you want to use the project, you can fill in the dataset path and destination path fields in the scripts/augmentation.py file remove the process you want to do from the comment, and generate your data.

For example

#saturation.process()
this line 
saturation.process()

saturation process by updating it in such a way. The same will be valid for other structures.
