### ISSUE TITLE
Why does the YOLOv8x model need to be downloaded after running the program?

### ISSUE THREAD

**Issue by xovow** [mmstfkc/yolov8-segmentation-augmentation#3]
![image](https://github.com/mmstfkc/yolov8-segmentation-augmentation/assets/78305714/e9e9e7f5-5607-4384-9015-8298635f6eaf)

**Comment by mmstfkc** [comment]
I thought it would be better with the detection of a specific class in the brightness process, so I didn't take that part to its original form. 

scripts/BlurryAndLightCheck.py:60

I've updated this area so that you don't need to download the model. If you want to use the model for Brightness or other operations, you can open this section again.
